name: aracra
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - r-base >=4.2,<4.3
  - sra-tools
  - hisat2
  - samtools
  - subread
  - trimmomatic
  - r-dplyr
  - r-readxl
  - r-ggplot2
  - r-ggrepel
  - r-stringr
  - r-jsonlite
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-sva
  - bioconductor-org.hs.eg.db
  - r-ggfortify
  - r-remotes
  - pip:
    - streamlit
    - pandas
    - numpy
    - psutil
    - openpyxl
